### PR TITLE
Fixes broken integration

### PR DESCRIPTION
**Pull request by JeremyKennedy**
No longer uses deprecated classes. Adds a version number.

### CODE REVIEW

**Comment by reffr** [comment]
I had to redo my home assistant. I tried reinstalling the aerogarden integration and I'm now again only getting the right side. Sorry to bother you with this but any ideas?

**Comment by JeremyKennedy** [comment]
I'm not sure what you mean by "only getting the right side". The integration still works for me, although I pretty much just use it to toggle the light.

**Comment by reffr** [comment]
Sorry. So, installed the integration and I can see all of the right sides of the garden but not the left side. They do not show up. I have no idea how I fixed this last time. I have tried uninstalling and installing the integration without success. 

Any ideas or insights you have would be greatly appreciated.

**Comment by JeremyKennedy** [comment]
Hmm, I didn't know Aerogardens had sides. It's quite possible that I've removed the code that handled that. Sorry, but I don't think I'll be able to help you with this.

**Comment by reffr** [comment]
That actually might be very helpful. I can try to go back and see what code was removed. 

Thanks,
Rob

**Pull request merged**
